#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Fri Nov 16 19:12:21 2018

@author: Mary
"""

#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Thu Nov 15 23:28:33 2018

@author: Jay
"""
#prefs.codegen.target='numpy'
from brian2 import *
import matplotlib.pyplot as plt

# input freq
inputfreq = array([240, 240, 400])

# tuning curve function
def neuron_tuning(si,spref):
    K=1
    g=30
    sigma=.8
    at= .8;
    lengthsi=size(si)
    tuneout=0.0*linspace(-pi,pi,lengthsi)
    for i in range(0,lengthsi):
       if cos(si[i]-spref) >at:
           tuneout[i]=(g/(1-at))*(cos(si[i]-spref)-at)
       else:
           tuneout[i]=0
    return tuneout

def freq2angle(freq, fmin, fmax):
    frange = fmax - fmin
    fdiff = freq - fmin
    fradian = (fdiff/frange)*2*pi
    return fradian


pref_frequency = [220.0 246.9 261.6 293.7 329.6 349.2 392.0]
# Izhikevich LTS neurons
a = 0.02
b = 0.2
c = -65
d = 0.5

# from bug model
tau_syn=1.0
g_synpk=0.4
g_synmaxval=(g_synpk/(tau_syn*exp(-1)))
Esyn = 40

neuron_eqs = '''
fchar : 1
I : 1

# Izhikevich model
dv/dt = (0.04*(v**2) + 5*v + 140 - u + I + g*(Esyn-v))/ms : 1
du/dt = a*(b*v - u)/ms : 1

# Alpha synapse model
dz/dt = (-z / tau_syn)/ms : 1
dg/dt = ((-g/tau_syn) + z)/ms : 1
'''

neuron_reset = '''
v = c
u = u + d
'''

# neurons activated by input frequency 
stimulus_neurons = NeuronGroup(200, neuron_eqs, clock=Clock(0.2*ms), threshold = "v>=30", reset = neuron_reset,method='euler')
stimulus_neurons.v = c
stimulus_neurons.u = c*b
stimulus_neurons.fchar = 220.0




for i in range (0, inputfreq.size):
    nA3.I = nA3.I + neuron_tuning(freq2angle(linspace(inputfreq[i],inputfreq[i],1),220,440),freq2angle(nA3.fchar,220,440))
    nB3.I = nB3.I + neuron_tuning(freq2angle(linspace(inputfreq[i],inputfreq[i],1),220,440),freq2angle(nB3.fchar,220,440))
    nC4.I = nC4.I + neuron_tuning(freq2angle(linspace(inputfreq[i],inputfreq[i],1),220,440),freq2angle(nC4.fchar,220,440))
    nD4.I = nD4.I + neuron_tuning(freq2angle(linspace(inputfreq[i],inputfreq[i],1),220,440),freq2angle(nD4.fchar,220,440))
    nE4.I = nE4.I + neuron_tuning(freq2angle(linspace(inputfreq[i],inputfreq[i],1),220,440),freq2angle(nE4.fchar,220,440))
    nF4.I = nF4.I + neuron_tuning(freq2angle(linspace(inputfreq[i],inputfreq[i],1),220,440),freq2angle(nF4.fchar,220,440))
    nG4.I = nG4.I + neuron_tuning(freq2angle(linspace(inputfreq[i],inputfreq[i],1),220,440),freq2angle(nG4.fchar,220,440))

si=np.linspace(220,440,1000)
curveA3=neuron_tuning(freq2angle(si,220,440),freq2angle(nA3.fchar,220,440))
curveB3=neuron_tuning(freq2angle(si,220,440),freq2angle(nB3.fchar,220,440))
curveC4=neuron_tuning(freq2angle(si,220,440),freq2angle(nC4.fchar,220,440))
curveD4=neuron_tuning(freq2angle(si,220,440),freq2angle(nD4.fchar,220,440))
curveE4=neuron_tuning(freq2angle(si,220,440),freq2angle(nE4.fchar,220,440))
curveF4=neuron_tuning(freq2angle(si,220,440),freq2angle(nF4.fchar,220,440))
curveG4=neuron_tuning(freq2angle(si,220,440),freq2angle(nG4.fchar,220,440))

# tuning curves
figure(1)
clf()
hold(True)
plot(si,curveA3)
plot(si,curveB3)
plot(si,curveC4)
plot(si,curveD4)
plot(si,curveE4)
plot(si,curveF4)
plot(si,curveG4)

# spike monitor
MA3 = StateMonitor(nA3, ('v','I'), record=True)
MB3 = StateMonitor(nB3, ('v','I'), record=True)
MC4 = StateMonitor(nC4, ('v','I'), record=True)
MD4 = StateMonitor(nD4, ('v','I'), record=True)
ME4 = StateMonitor(nE4, ('v','I'), record=True)
MF4 = StateMonitor(nF4, ('v','I'), record=True)
MG4 = StateMonitor(nG4, ('v','I'), record=True)

smA3 = SpikeMonitor(nA3)
smB3 = SpikeMonitor(nB3)
smC4 = SpikeMonitor(nC4)
smD4 = SpikeMonitor(nD4)
smE4 = SpikeMonitor(nE4)
smF4 = SpikeMonitor(nF4)
smG4 = SpikeMonitor(nG4)

run(100*ms,report='text')

figure(2)
clf()
subplot(4,2,1)
plot(MA3.t/ms, MA3.v[0])
subplot(4,2,2)
plot(MB3.t/ms, MB3.v[0])
subplot(4,2,3)
plot(MC4.t/ms, MC4.v[0])
subplot(4,2,4)
plot(MD4.t/ms, MD4.v[0])
subplot(4,2,5)
plot(ME4.t/ms, ME4.v[0])
subplot(4,2,6)
plot(MF4.t/ms, MF4.v[0])
subplot(4,2,7)
plot(MG4.t/ms, MG4.v[0])

figure(3)
clf()
subplot(4,2,1)
plot(MA3.t/ms, MA3.I[0])
subplot(4,2,2)
plot(MB3.t/ms, MB3.I[0])
subplot(4,2,3)
plot(MC4.t/ms, MC4.I[0])
subplot(4,2,4)
plot(MD4.t/ms, MD4.I[0])
subplot(4,2,5)
plot(ME4.t/ms, ME4.I[0])
subplot(4,2,6)
plot(MF4.t/ms, MF4.I[0])
subplot(4,2,7)
plot(MG4.t/ms, MG4.I[0])

figure(4)
clf()
hold(True)
plot(smA3.t/ms, smA3.i+1, 'k*')
plot(smB3.t/ms, smB3.i+2, 'k*')
plot(smC4.t/ms, smC4.i+3, 'k*')
plot(smD4.t/ms, smD4.i+4, 'k*')
plot(smE4.t/ms, smE4.i+5, 'k*')
plot(smF4.t/ms, smF4.i+6, 'k*')
plot(smG4.t/ms, smG4.i+7, 'k*')
ylim(0, 8)
yticks(np.arange(8), ('', 'A3', 'B3', 'C4', 'D4', 'E4', 'F4', 'G4'))


